CC=clang
CPPFLAGS=-I/usr/local/include -I/opt/local/include -Iother
CPPFLAGS+=-D_NSIG=NSIG -DHAVE_STRLCAT
CFLAGS=-Wall -Wno-pointer-sign -pedantic -std=c99 -O2
LDFLAGS=-L/usr/local/lib -L/opt/local/lib -lsodium

OBJS=reop.o other/other.o

reop: ${OBJS}
	${CC} ${OBJS} ${LDFLAGS} -o reop

clean:
	rm -f ${OBJS} reop

.SUFFIXES: .c .o
.c.o:
	${CC} ${CPPFLAGS} ${CFLAGS} -c $< -o $@
